services:
  - type: web
    name: agendapro
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/agendapro-0.0.1-SNAPSHOT.jar"
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: nome-do-seu-banco-de-dados # <-- MUDE AQUI
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: gendapro_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: gendapro_db
          property: password