CREATE TABLE agendamentos (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                              nome VARCHAR(255),
                              telefone VARCHAR(255),
                              data_hora TIMESTAMP,
                              PRIMARY KEY (id)
);